# Generated by Django X.Y on YYYY-MM-DD HH:MM

from django.db import migrations, models
import django.utils.timezone
from django.conf import settings

def set_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    default_user = User.objects.get(username='defaultuser')
    SavingsData = apps.get_model('main', 'SavingsData')
    SavingsData.objects.filter(user__isnull=True).update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_user),
    ]
