# Generated by Django 5.1.2 on 2024-11-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_goalplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalplan",
            name="goal_months",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="goalplan",
            name="income",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="goalplan",
            name="percentage_towards_goal",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="goalplan",
            name="subtracted_values",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="goal_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="goal_name",
            field=models.CharField(default="Default Goal Name", max_length=255),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="saved_amount",
            field=models.FloatField(default=0.0),
        ),
    ]
