# Generated by Django 5.1.2 on 2024-11-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_goalplan_goal_months_goalplan_income_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalplan",
            name="goal_amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="goal_months",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="goal_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="income",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="percentage_towards_goal",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="saved_amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="subtracted_values",
            field=models.TextField(),
        ),
    ]
