# Generated by Django 5.1.2 on 2024-11-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_goalplan_goal_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalplan",
            name="subtracted_values",
            field=models.JSONField(),
        ),
    ]
