# Generated by Django 5.1.2 on 2024-11-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_goalplan_subtracted_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goalplan",
            name="saved_amount",
        ),
    ]
