# Generated by Django 5.1.2 on 2024-11-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_rename_goal_months_goalplan_monthly_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalplan",
            name="goal_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="goalplan",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
